# Generated by Django 4.2.3 on 2023-07-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_accounts",
            name="is_calculator",
            field=models.BooleanField(default=False, verbose_name="حسابدار"),
        ),
        migrations.AddField(
            model_name="user_accounts",
            name="is_inventor",
            field=models.BooleanField(default=False, verbose_name="انبار دار"),
        ),
        migrations.AlterField(
            model_name="user_accounts",
            name="codeMelli",
            field=models.CharField(max_length=20, unique=True, verbose_name="کد ملی"),
        ),
    ]
