# Generated by Django 4.2.3 on 2023-07-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_user_accounts_is_calculator_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_accounts",
            name="status",
            field=models.BooleanField(default=False, verbose_name="وضعیت"),
        ),
    ]
