# Generated by Django 4.2.3 on 2023-07-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_user_accounts_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_accounts",
            name="last_activity",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
