# Generated by Django 4.2.3 on 2023-07-22 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialscardex',
            name='status',
            field=models.BooleanField(blank=True, null=True, verbose_name='ورودی / خروجی'),
        ),
        migrations.AddField(
            model_name='productscardex',
            name='status',
            field=models.BooleanField(blank=True, null=True, verbose_name='ورودی / خروجی'),
        ),
    ]
