# Generated by Django 4.2.3 on 2023-07-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_materialscardex_status_productscardex_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialscardex',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='productscardex',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
