# Generated by Django 4.2.3 on 2023-07-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_materialscardex_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialscardex',
            name='factor_row',
            field=models.CharField(default=1, max_length=50, verbose_name='ردیف فاکتور'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productscardex',
            name='factor_row',
            field=models.CharField(default=5, max_length=50, verbose_name='ردیف فاکتور'),
            preserve_default=False,
        ),
    ]
