# Generated by Django 4.2.3 on 2023-07-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_materialscardex_factor_row_productscardex_factor_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='row',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='row',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
