# Generated by Django 4.2.3 on 2023-07-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_materials_row_products_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialscardex',
            name='public_key',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='کاندید'),
        ),
        migrations.AddField(
            model_name='productscardex',
            name='public_key',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='کاندید'),
        ),
    ]
